language: julia
os:
    - osx
    - linux
    - windows
julia:
    - 1.0
    - 1.4 # explicitly specify 1.4 instead of 1 as a workaround
    - nightly
notifications:
    email: false
jobs:
  include:
    - julia: 1
      os: linux
      arch: x86
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
